branch-defaults:
  master:
    environment: cksc-backend-apis
environment-defaults:
  cksc-backend-apis:
    branch: null
    repository: null
global:
  application_name: cksc-backend-apis
  default_ec2_keyname: null
  default_platform: Node.js 20
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
